# fly.toml app configuration file generated for claude-backup on 2026-05-29T11:57:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'claude-backup'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[env]
  NODE_ENV = 'production'

[processes]
  app = ''

[[mounts]]
  source = 'claude_backup_data'
  destination = '/data'
  initial_size = '1'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
